1.Let’s attempt to predict the survival of a horse based on various observed medical conditions. 

Load the data from ‘horses.csv’ and observe whether it contains missing values.[Hint: Pandas dataframe has a method isnull]

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
horse=pd.read_csv('horse.csv')
horse.head(2)

surgery    age  hospital_number  rectal_temp  pulse  respiratory_rate   
0      no  adult           530101         38.5   66.0              28.0  \
1     yes  adult           534817         39.2   88.0              20.0   

  temp_of_extremities peripheral_pulse mucous_membrane capillary_refill_time   
0                cool          reduced             NaN            more_3_sec  \
1                 NaN              NaN   pale_cyanotic            less_3_sec   

   ... packed_cell_volume total_protein abdomo_appearance abdomo_protein   
0  ...               45.0           8.4               NaN            NaN  \
1  ...               50.0          85.0            cloudy            2.0   

      outcome  surgical_lesion lesion_1 lesion_2  lesion_3  cp_data  
0        died               no    11300        0         0       no  
1  euthanized               no     2208        0         0       no  

[2 rows x 28 columns]

In [3]:
horse.shape

(299, 28)

In [4]:
horse.isnull().sum()

surgery                    0
age                        0
hospital_number            0
rectal_temp               60
pulse                     24
respiratory_rate          58
temp_of_extremities       56
peripheral_pulse          69
mucous_membrane           47
capillary_refill_time     32
pain                      55
peristalsis               44
abdominal_distention      56
nasogastric_tube         104
nasogastric_reflux       106
nasogastric_reflux_ph    246
rectal_exam_feces        102
abdomen                  118
packed_cell_volume        29
total_protein             33
abdomo_appearance        165
abdomo_protein           198
outcome                    0
surgical_lesion            0
lesion_1                   0
lesion_2                   0
lesion_3                   0
cp_data                    0
dtype: int64

In [5]:
horse['surgery'].unique()

array(['no', 'yes'], dtype=object)

In [6]:

pd.get_dummies(horse['surgery'])

no    yes
0     True  False
1    False   True
2     True  False
3    False   True
4     True  False
..     ...    ...
294  False   True
295   True  False
296  False   True
297  False   True
298  False   True

[299 rows x 2 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
lb.fit_transform(horse['surgery'])

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1])

In [8]:
#or we can use map here as there are only 2 categories i.e yes and no
#horse['surgery']=horse['surgery'].map({'yes':1,'no':0})

## for multiple categorical feature we will separate first the categorical feature and numerocal feature

In [9]:
horse['peripheral_pulse'].dtype

dtype('O')

In [10]:
horse.columns

Index(['surgery', 'age', 'hospital_number', 'rectal_temp', 'pulse',
       'respiratory_rate', 'temp_of_extremities', 'peripheral_pulse',
       'mucous_membrane', 'capillary_refill_time', 'pain', 'peristalsis',
       'abdominal_distention', 'nasogastric_tube', 'nasogastric_reflux',
       'nasogastric_reflux_ph', 'rectal_exam_feces', 'abdomen',
       'packed_cell_volume', 'total_protein', 'abdomo_appearance',
       'abdomo_protein', 'outcome', 'surgical_lesion', 'lesion_1', 'lesion_2',
       'lesion_3', 'cp_data'],
      dtype='object')

In [11]:
categorical_feat=[]
numerical_feat=[]
for i in horse.columns:
    if horse[i].dtype=='O':
        categorical_feat.append(i)
    else:
        
        numerical_feat.append(i)

In [12]:
categorical_feat

['surgery',
 'age',
 'temp_of_extremities',
 'peripheral_pulse',
 'mucous_membrane',
 'capillary_refill_time',
 'pain',
 'peristalsis',
 'abdominal_distention',
 'nasogastric_tube',
 'nasogastric_reflux',
 'rectal_exam_feces',
 'abdomen',
 'abdomo_appearance',
 'outcome',
 'surgical_lesion',
 'cp_data']

In [13]:
numerical_feat

['hospital_number',
 'rectal_temp',
 'pulse',
 'respiratory_rate',
 'nasogastric_reflux_ph',
 'packed_cell_volume',
 'total_protein',
 'abdomo_protein',
 'lesion_1',
 'lesion_2',
 'lesion_3']

In [14]:
for i in categorical_feat:
    horse[i]=lb.fit_transform(horse[i])

In [15]:
horse.head(4)

surgery  age  hospital_number  rectal_temp  pulse  respiratory_rate   
0        0    0           530101         38.5   66.0              28.0  \
1        1    0           534817         39.2   88.0              20.0   
2        0    0           530334         38.3   40.0              24.0   
3        1    1          5290409         39.1  164.0              84.0   

   temp_of_extremities  peripheral_pulse  mucous_membrane   
0                    1                 3                6  \
1                    4                 4                4   
2                    2                 2                5   
3                    0                 2                2   

   capillary_refill_time  ...  packed_cell_volume  total_protein   
0                      2  ...                45.0            8.4  \
1                      1  ...                50.0           85.0   
2                      1  ...                33.0            6.7   
3                      2  ...                48.0            7.2   

   abdomo_appearance  abdomo_protein  outcome  surgical_lesion  lesion_1   
0                  3             NaN        0                0     11300  \
1                  1             2.0        1                0      2208   
2                  3             NaN        2                0         0   
3                  2             5.3        0                1      2208   

   lesion_2  lesion_3  cp_data  
0         0         0        0  
1         0         0        0  
2         0         0        1  
3         0         0        1  

[4 rows x 28 columns]

In [16]:
horse.isnull().sum()

surgery                    0
age                        0
hospital_number            0
rectal_temp               60
pulse                     24
respiratory_rate          58
temp_of_extremities        0
peripheral_pulse           0
mucous_membrane            0
capillary_refill_time      0
pain                       0
peristalsis                0
abdominal_distention       0
nasogastric_tube           0
nasogastric_reflux         0
nasogastric_reflux_ph    246
rectal_exam_feces          0
abdomen                    0
packed_cell_volume        29
total_protein             33
abdomo_appearance          0
abdomo_protein           198
outcome                    0
surgical_lesion            0
lesion_1                   0
lesion_2                   0
lesion_3                   0
cp_data                    0
dtype: int64

Replace the missing values with the most frequent value in each column

.[Hint: Refer to Imputer class in Scikit learn preprocessing module]

In [20]:
horse['rectal_temp'].unique()

array([38.5, 39.2, 38.3, 39.1, 37.3,  nan, 37.9, 38.1, 37.2, 38. , 38.2,
       37.6, 37.5, 39.4, 39.9, 38.4, 38.6, 37.8, 37.7, 39. , 35.4, 38.9,
       37.4, 40.3, 37. , 39.7, 38.7, 36.4, 38.8, 39.6, 36.8, 39.5, 36.5,
       36. , 37.1, 39.3, 36.1, 36.6, 40.8, 36.9, 40. ])

In [22]:
horse['rectal_temp'] = horse['rectal_temp'].fillna(horse['rectal_temp'].mode()[0])

In [23]:
horse['rectal_temp'].unique()

array([38.5, 39.2, 38.3, 39.1, 37.3, 38. , 37.9, 38.1, 37.2, 38.2, 37.6,
       37.5, 39.4, 39.9, 38.4, 38.6, 37.8, 37.7, 39. , 35.4, 38.9, 37.4,
       40.3, 37. , 39.7, 38.7, 36.4, 38.8, 39.6, 36.8, 39.5, 36.5, 36. ,
       37.1, 39.3, 36.1, 36.6, 40.8, 36.9, 40. ])

In [24]:
horse['pulse'] = horse['pulse'].fillna(horse['pulse'].mode()[0])

In [25]:
horse['respiratory_rate'] = horse['respiratory_rate'].fillna(horse['respiratory_rate'].mode()[0])

In [26]:
horse['nasogastric_reflux_ph'] = horse['nasogastric_reflux_ph'].fillna(horse['nasogastric_reflux_ph'].mode()[0])

In [27]:
horse['packed_cell_volume'] = horse['packed_cell_volume'].fillna(horse['packed_cell_volume'].mode()[0])

In [28]:
horse['abdomo_protein'] = horse['abdomo_protein'].fillna(horse['abdomo_protein'].mode()[0])

In [29]:
horse['total_protein'] = horse['total_protein'].fillna(horse['total_protein'].mode()[0])

In [30]:
horse.isnull().sum()

surgery                  0
age                      0
hospital_number          0
rectal_temp              0
pulse                    0
respiratory_rate         0
temp_of_extremities      0
peripheral_pulse         0
mucous_membrane          0
capillary_refill_time    0
pain                     0
peristalsis              0
abdominal_distention     0
nasogastric_tube         0
nasogastric_reflux       0
nasogastric_reflux_ph    0
rectal_exam_feces        0
abdomen                  0
packed_cell_volume       0
total_protein            0
abdomo_appearance        0
abdomo_protein           0
outcome                  0
surgical_lesion          0
lesion_1                 0
lesion_2                 0
lesion_3                 0
cp_data                  0
dtype: int64

In [31]:
horse.head(2)

surgery  age  hospital_number  rectal_temp  pulse  respiratory_rate   
0        0    0           530101         38.5   66.0              28.0  \
1        1    0           534817         39.2   88.0              20.0   

   temp_of_extremities  peripheral_pulse  mucous_membrane   
0                    1                 3                6  \
1                    4                 4                4   

   capillary_refill_time  ...  packed_cell_volume  total_protein   
0                      2  ...                45.0            8.4  \
1                      1  ...                50.0           85.0   

   abdomo_appearance  abdomo_protein  outcome  surgical_lesion  lesion_1   
0                  3             2.0        0                0     11300  \
1                  1             2.0        1                0      2208   

   lesion_2  lesion_3  cp_data  
0         0         0        0  
1         0         0        0  

[2 rows x 28 columns]

In [32]:
horse.columns

Index(['surgery', 'age', 'hospital_number', 'rectal_temp', 'pulse',
       'respiratory_rate', 'temp_of_extremities', 'peripheral_pulse',
       'mucous_membrane', 'capillary_refill_time', 'pain', 'peristalsis',
       'abdominal_distention', 'nasogastric_tube', 'nasogastric_reflux',
       'nasogastric_reflux_ph', 'rectal_exam_feces', 'abdomen',
       'packed_cell_volume', 'total_protein', 'abdomo_appearance',
       'abdomo_protein', 'outcome', 'surgical_lesion', 'lesion_1', 'lesion_2',
       'lesion_3', 'cp_data'],
      dtype='object')

In [33]:
horse['cp_data'].unique()

array([0, 1])

## 4.Fit a decision tree classifier and observe the accuracy.

In [34]:
x=horse.iloc[:,:-1]
y=horse['cp_data']

In [35]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(max_depth=10)


In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=82)

In [37]:
dt.fit(X_train,Y_train)

DecisionTreeClassifier(max_depth=10)

In [38]:
y_pred=dt.predict(X_test)

In [40]:
horse['cp_data'].value_counts()# imbalanced dataset

cp_data
0    200
1     99
Name: count, dtype: int64

In [45]:
from sklearn.metrics import precision_score,recall_score,accuracy_score

In [52]:
precision_score(Y_test,y_pred)

0.6818181818181818

In [53]:
recall_score(Y_test,y_pred)

0.6818181818181818

In [55]:
accuracy_score(Y_test,y_pred)

0.7666666666666667

## 5. Fit a random forest classifier and observe the accuracy.

In [47]:
from sklearn.ensemble import RandomForestClassifier
rd=RandomForestClassifier()

In [48]:
rd.fit(X_train,Y_train)

RandomForestClassifier()

In [49]:
y_pred2=rd.predict(X_test)

In [50]:
accuracy_score(Y_test,y_pred2)

0.8

In [51]:
precision_score(Y_test,y_pred2)

0.7777777777777778

In [56]:
#we can see how random_forest classifier fits well here and the accuracy score increases